version: "2"
services:
  unity-android:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        UNITY_VERSION: 2021.2.12f1
        IMAGE_PLATFORM: android
        BUILD_TARGET: android
        UNITY_LICENSE: ${UNITY_LICENSE}
    image: unity-android
    volumes:
      - $PWD:/mnt
    environment:
      JOB_NAME: build-apk
