env:
  COMPANY: qkrsogusl3
  PRODUCT_NAME: AppBuilder
input:
  Key: value
groups:
  first: 
    - print:
        message: first-1
    - print: 
        message: first-2
  second:
    - print: 
        message: s
works:
  first:
    platform: android
    steps:
      - print:
          message: work test
  group-test:
    platform: android
    steps:
      - first
      - print: 
          message: second
  build-apk:
    platform: android
    steps:
      - player-settings:
          company-name: $(COMPANY)
          product-name: $(PRODUCT_NAME)
      - player-settings-android:
          package-name: com.$(COMPANY).$(PRODUCT_NAME)
          architectures: !architectures
            - "ARMv7"
            - "ARM64"
      - build:
          path: $(PROJECT_PATH)/Build/$(PLATFORM)/$(PRODUCT_NAME)