name: update Actions.md

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'Packages/UActions/Editor/Actions/**/*.cs'
    - 'ActionsDocExporter/ActionsDocExporter/**/*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: export Actions.md
      run: dotnet run --project ./ActionsDocExporter/ActionsDocExporter -- --base-path $(pwd) --dest-path "Actions.md" --actions-docs-path "Documents/Actions"
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update Actions.md
    
